In [1]:
124341342**100

289437657159816160291931685301549134875715811806077725714830003776267785682274226323106051805486547024011325586702136571893734854579421745283047582729662329924773144958469051035430412291681389322950721231947002760531507991436975887512187526463391542865790918100245769074256225678385904247462307633129914169552670311238320130470112548798834847273871776502142578108656766613701809255132280020635524832458179979756270155824553156921817340238277741765822917998529364868416518364960675510751560541881622324553639568111328253146464861869591210746146451795947783018036749309527129315898351397252653774184946360182076167244286041082064399288472572185919972722591537843933722214441014345245468824982035957246466149084711932010191476337942460107449567826892613608562866706174146192076748912903100401652373978379112677376

# Exercise: working with Jupyter Notebook
1. Use the '+' botton to add new cell under the current one
2. type the following code and run it by using <kbd>Shift</kbd> + <kbd>Enter</kbd>:

        import pandas as pd
        pandas.read_csv('Data/Abalone.csv')
        
3. Getting used to Keyboard shortcuts:
        
     - <kbd>Esc</kbd>
     - <kbd>b</kbd>
     - <kbd>m</kbd>
     - <kbd>Enter</kbd>
     - <kbd>Ctrl</kbd> + <kbd>Shift</kbd>
     - <kbd>a</kbd>
     - <kbd>Enter</kbd>
     - <kbd>10**0.005</kbd>
     - <kbd>Shift</kbd> + <kbd>Enter</kbd>
     - <kbd>Esc</kbd>
     - <kbd>h</kbd>

In [7]:
import pandas as pd
pd.read_csv('Data/Abalone.csv')

,Unnamed: 0,sex,length,diameter,height,whole weight,shucked weight,viscera weight,shell weight,rings
0,0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.1500,15
1,1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.0700,7
2,2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.2100,9
3,3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.1550,10
4,4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.0550,7
5,5,I,0.425,0.300,0.095,0.3515,0.1410,0.0775,0.1200,8
6,6,F,0.530,0.415,0.150,0.7775,0.2370,0.1415,0.3300,20
7,7,F,0.545,0.425,0.125,0.7680,0.2940,0.1495,0.2600,16
8,8,M,0.475,0.370,0.125,0.5095,0.2165,0.1125,0.1650,9
9,9,F,0.550,0.440,0.150,0.8945,0.3145,0.1510,0.3200,19
10,10,F,0.525,0.380,0.140,0.6065,0.1940,0.1475,0.2100,14
11,11,M,0.430,0.350,0.110,0.4060,0.1675,0.0810,0.1350,10
12,12,M,0.490,0.380,0.135,0.5415,0.2175,0.0950,0.1900,11
13,13,F,0.535,0.405,0.145,0.6845,0.2725,0.1710,0.2050,10
14,14,F,0.470,0.355,0.100,0.4755,0.1675,0.0805,0.1850,10
15,15,M,0.500,0.400,0.130,0.6645,0.2580,0.1330,0.2400,12
16,16,I,0.355,0.280,0.085,0.2905,0.0950,0.0395,0.1150,7
17,17,F,0.440,0.340,0.100,0.4510,0.1880,0.0870,0.1300,10
18,18,M,0.365,0.295,0.080,0.2555,0.0970,0.0430,0.1000,7
19,19,M,0.450,0.320,0.100,0.3810,0.1705,0.0750,0.1150,9
20,20,M,0.355,0.280,0.095,0.2455,0.0955,0.0620,0.0750,11
21,21,I,0.380,0.275,0.100,0.2255,0.0800,0.0490,0.0850,10
22,22,F,0.565,0.440,0.155,0.9395,0.4275,0.2140,0.2700,12
23,23,F,0.550,0.415,0.135,0.7635,0.3180,0.2100,0.2000,9
24,24,F,0.615,0.480,0.165,1.1615,0.5130,0.3010,0.3050,10
25,25,F,0.560,0.440,0.140,0.9285,0.3825,0.1880,0.3000,11
26,26,F,0.580,0.450,0.185,0.9955,0.3945,0.2720,0.2850,11
27,27,M,0.590,0.445,0.140,0.9310,0.3560,0.2340,0.2800,12
28,28,M,0.605,0.475,0.180,0.9365,0.3940,0.2190,0.2950,15
29,29,M,0.575,0.425,0.140,0.8635,0.3930,0.2270,0.2000,11
...,...,...,...,...,...,...,...,...,...,...
4147,4147,M,0.695,0.550,0.195,1.6645,0.7270,0.3600,0.4450,11
4148,4148,M,0.770,0.605,0.175,2.0505,0.8005,0.5260,0.3550,11
4149,4149,I,0.280,0.215,0.070,0.1240,0.0630,0.0215,0.0300,6
4150,4150,I,0.330,0.230,0.080,0.1400,0.0565,0.0365,0.0460,7
4151,4151,I,0.350,0.250,0.075,0.1695,0.0835,0.0355,0.0410,6
4152,4152,I,0.370,0.280,0.090,0.2180,0.0995,0.0545,0.0615,7
4153,4153,I,0.430,0.315,0.115,0.3840,0.1885,0.0715,0.1100,8
4154,4154,I,0.435,0.330,0.095,0.3930,0.2190,0.0750,0.0885,6
4155,4155,I,0.440,0.350,0.110,0.3805,0.1575,0.0895,0.1150,6
4156,4156,M,0.475,0.370,0.110,0.4895,0.2185,0.1070,0.1460,8
4157,4157,M,0.475,0.360,0.140,0.5135,0.2410,0.1045,0.1550,8
4158,4158,I,0.480,0.355,0.110,0.4495,0.2010,0.0890,0.1400,8
4159,4159,F,0.560,0.440,0.135,0.8025,0.3500,0.1615,0.2590,9
4160,4160,F,0.585,0.475,0.165,1.0530,0.4580,0.2170,0.3000,11
4161,4161,F,0.585,0.455,0.170,0.9945,0.4255,0.2630,0.2845,11
4162,4162,M,0.385,0.255,0.100,0.3175,0.1370,0.0680,0.0920,8
4163,4163,I,0.390,0.310,0.085,0.3440,0.1810,0.0695,0.0790,7
4164,4164,I,0.390,0.290,0.100,0.2845,0.1255,0.0635,0.0810,7
4165,4165,I,0.405,0.300,0.085,0.3035,0.1500,0.0505,0.0880,7
4166,4166,I,0.475,0.365,0.115,0.4990,0.2320,0.0885,0.1560,10
4167,4167,M,0.500,0.380,0.125,0.5770,0.2690,0.1265,0.1535,9
4168,4168,F,0.515,0.400,0.125,0.6150,0.2865,0.1230,0.1765,8
4169,4169,M,0.520,0.385,0.165,0.7910,0.3750,0.1800,0.1815,10
4170,4170,M,0.550,0.430,0.130,0.8395,0.3155,0.1955,0.2405,10
4171,4171,M,0.560,0.430,0.155,0.8675,0.4000,0.1720,0.2290,8
4172,4172,F,0.565,0.450,0.165,0.8870,0.3700,0.2390,0.2490,11
4173,4173,M,0.590,0.440,0.135,0.9660,0.4390,0.2145,0.2605,10
4174,4174,M,0.600,0.475,0.205,1.1760,0.5255,0.2875,0.3080,9
4175,4175,F,0.625,0.485,0.150,1.0945,0.5310,0.2610,0.2960,10
4176,4176,M,0.710,0.555,0.195,1.9485,0.9455,0.3765,0.4950,12

###### Trying some keyboard shortcuts

In [10]:
10**0.005

1.0115794542598986

In [11]:
print?

In [13]:
pd.read_csv?

In [14]:
open('Data/abalone.csv')

## Basic Python types

In [15]:
# integers: +ve or -ve whole numbers:

10086786

10086786

In [16]:
# floats: numbers with decimal points:

3.14

3.14

In [17]:
'C:\Users\ABD01F'

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-17-62f75e52288d>, line 1)

In [18]:
r'C:\Users\ABD01F'

'C:\\Users\\ABD01F'

In [19]:
print(r'C:\Users\ABD01F')

C:\Users\ABD01F

In [33]:
def great(name):
    print('Good morning ' + name + '!')

In [34]:
great('Muhammad')

Good morning Muhammad!

In [37]:
def imperial_to_metric(feet, inches): # positional arguments
    total_inches = feet * 12 + inches
    cms = total_inches * 2.54
    return(cms / 100)

In [44]:
height = imperial_to_metric(5, 6)

In [45]:
height

1.6764000000000001

In [46]:
def imperial_to_metric(feet=0, inches=0): # keyword arguments
    total_inches = feet * 12 + inches
    cms = total_inches * 2.54
    return(cms / 100)

In [47]:
imperial_to_metric(0, 10)

0.254

In [48]:
imperial_to_metric(inches=10)

0.254

In [77]:
def F_to_C(degrees_F, Kelvin_offset=0):
    degrees_C = (degrees_F-32) * (5/9)
    degrees_K = degrees_C + Kelvin_offset
    return degrees_C + degrees_K

In [78]:
F_to_C(-10, 273.15)

226.4833333333333

In [79]:
F_to_C(0, 273.15)

237.59444444444443

In [80]:
F_to_C(100, 273.15)

348.7055555555555

In [81]:
import numpy as np

temperatures = np.arange(-100, 100)

In [82]:
temperatures

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,
        -89,  -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,
        -78,  -77,  -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,
        -67,  -66,  -65,  -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,
        -56,  -55,  -54,  -53,  -52,  -51,  -50,  -49,  -48,  -47,  -46,
        -45,  -44,  -43,  -42,  -41,  -40,  -39,  -38,  -37,  -36,  -35,
        -34,  -33,  -32,  -31,  -30,  -29,  -28,  -27,  -26,  -25,  -24,
        -23,  -22,  -21,  -20,  -19,  -18,  -17,  -16,  -15,  -14,  -13,
        -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,   -4,   -3,   -2,
         -1,    0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
         10,   11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

In [83]:
F_to_C(temperatures)

array([-146.66666667, -145.55555556, -144.44444444, -143.33333333,
       -142.22222222, -141.11111111, -140.        , -138.88888889,
       -137.77777778, -136.66666667, -135.55555556, -134.44444444,
       -133.33333333, -132.22222222, -131.11111111, -130.        ,
       -128.88888889, -127.77777778, -126.66666667, -125.55555556,
       -124.44444444, -123.33333333, -122.22222222, -121.11111111,
       -120.        , -118.88888889, -117.77777778, -116.66666667,
       -115.55555556, -114.44444444, -113.33333333, -112.22222222,
       -111.11111111, -110.        , -108.88888889, -107.77777778,
       -106.66666667, -105.55555556, -104.44444444, -103.33333333,
       -102.22222222, -101.11111111, -100.        ,  -98.88888889,
        -97.77777778,  -96.66666667,  -95.55555556,  -94.44444444,
        -93.33333333,  -92.22222222,  -91.11111111,  -90.        ,
        -88.88888889,  -87.77777778,  -86.66666667,  -85.55555556,
        -84.44444444,  -83.33333333,  -82.22222222,  -81.11111111,
        -80.        ,  -78.88888889,  -77.77777778,  -76.66666667,
        -75.55555556,  -74.44444444,  -73.33333333,  -72.22222222,
        -71.11111111,  -70.        ,  -68.88888889,  -67.77777778,
        -66.66666667,  -65.55555556,  -64.44444444,  -63.33333333,
        -62.22222222,  -61.11111111,  -60.        ,  -58.88888889,
        -57.77777778,  -56.66666667,  -55.55555556,  -54.44444444,
        -53.33333333,  -52.22222222,  -51.11111111,  -50.        ,
        -48.88888889,  -47.77777778,  -46.66666667,  -45.55555556,
        -44.44444444,  -43.33333333,  -42.22222222,  -41.11111111,
        -40.        ,  -38.88888889,  -37.77777778,  -36.66666667,
        -35.55555556,  -34.44444444,  -33.33333333,  -32.22222222,
        -31.11111111,  -30.        ,  -28.88888889,  -27.77777778,
        -26.66666667,  -25.55555556,  -24.44444444,  -23.33333333,
        -22.22222222,  -21.11111111,  -20.        ,  -18.88888889,
        -17.77777778,  -16.66666667,  -15.55555556,  -14.44444444,
        -13.33333333,  -12.22222222,  -11.11111111,  -10.        ,
         -8.88888889,   -7.77777778,   -6.66666667,   -5.55555556,
         -4.44444444,   -3.33333333,   -2.22222222,   -1.11111111,
          0.        ,    1.11111111,    2.22222222,    3.33333333,
          4.44444444,    5.55555556,    6.66666667,    7.77777778,
          8.88888889,   10.        ,   11.11111111,   12.22222222,
         13.33333333,   14.44444444,   15.55555556,   16.66666667,
         17.77777778,   18.88888889,   20.        ,   21.11111111,
         22.22222222,   23.33333333,   24.44444444,   25.55555556,
         26.66666667,   27.77777778,   28.88888889,   30.        ,
         31.11111111,   32.22222222,   33.33333333,   34.44444444,
         35.55555556,   36.66666667,   37.77777778,   38.88888889,
         40.        ,   41.11111111,   42.22222222,   43.33333333,
         44.44444444,   45.55555556,   46.66666667,   47.77777778,
         48.88888889,   50.        ,   51.11111111,   52.22222222,
         53.33333333,   54.44444444,   55.55555556,   56.66666667,
         57.77777778,   58.88888889,   60.        ,   61.11111111,
         62.22222222,   63.33333333,   64.44444444,   65.55555556,
         66.66666667,   67.77777778,   68.88888889,   70.        ,
         71.11111111,   72.22222222,   73.33333333,   74.44444444])

In [117]:
def metric_to_imperial(meters):
    cms = meters * 100
    total_inches = cms / 2.54
    feet = total_inches // 12
    inches = total_inches % 12
    return feet, inches

In [118]:
metric_to_imperial(1.68)

(5.0, 6.141732283464563)

In [120]:
! pip install emoji # the ! is a shortcut to run the command in the terminal

Collecting emoji
  Downloading https://files.pythonhosted.org/packages/9c/fb/7586e11ff9205c9be9d11d376fcb6990ec4bdfae0a35663fb1ada7e3c10f/emoji-0.5.1-py3-none-any.whl
Installing collected packages: emoji
Successfully installed emoji-0.5.1

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
altair 2.2.2 requires typing, which is not installed.
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

In [121]:
! python -m pip install --upgrade pip

Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-18.1

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
altair 2.2.2 requires typing, which is not installed.

In [122]:
import emoji

In [123]:
print(emoji.emojize(':snake: are :thumbs_up:'))

🐍 are 👍

In [124]:
%%writefile unit_conversion.py  # saves the code into *.py file

def metric_to_imperial(meters):
    cms = meters * 100
    total_inches = cms / 2.54
    feet = total_inches // 12
    inches = total_inches % 12
    return feet, inches

Writing unit_conversion.py

In [125]:
import unit_conversion # you can import the *.py file then as if it is a library/package

In [126]:
unit_conversion.metric_to_imperial(100)

(328.0, 1.0078740157478023)

In [128]:
import importlib                    # reloads the *.py file with the new updates in the file
importlib.reload(unit_conversion)

In [129]:
unit_conversion.imperial_to_metric(300, 5)

91.56700000000001

In [130]:
import sys
sys.path

['',
 'C:\\Users\\ABD01F\\Documents\\Python Charmers',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\python37.zip',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\DLLs',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\ABD01F\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ABD01F\\.ipython']

# Source control - avoiding the "Oh shit" moment

The idea is to snapshot at a certian point in time, so you can revert to that point at any time in the future - even if you deleted the file

common source control tool is "git" - it has 4 key commands and there are lots of GUIs so you can do it w/out the command line as well.

1. git add
2. git commit
3. git pull
4. git push

# Back to Python...

## Collections:

In [131]:
# a list is an ordered collection of data

names = []

In [132]:
front_raw = ['Greg', 'Julian', 'Seline', 'Oceane']

### Excercise: Adding data to a list

All Python objects have 'methods' - functions that work on just that object. they are accessed via dot notation

In [133]:
front_raw.append('Muhammad')

In [134]:
front_raw

['Greg', 'Julian', 'Seline', 'Oceane', 'Muhammad']

In [135]:
second_raw = ['Muhammad', 'Dave', 'Beven', 'Alex']

In [136]:
front_raw.append(second_raw)

In [137]:
front_raw

['Greg',
 'Julian',
 'Seline',
 'Oceane',
 'Muhammad',
 ['Muhammad', 'Dave', 'Beven', 'Alex']]

In [138]:
front_raw.remove(second_raw)

In [139]:
front_raw

['Greg', 'Julian', 'Seline', 'Oceane', 'Muhammad']

In [140]:
front_raw.extend(second_raw)

In [141]:
front_raw

['Greg',
 'Julian',
 'Seline',
 'Oceane',
 'Muhammad',
 'Muhammad',
 'Dave',
 'Beven',
 'Alex']

In [147]:
front_raw.append?

## Indexing - getting data out of collection

in Python are 2 ways to referance data

1.
2. Key based index

In [148]:
front_raw[1]

'Julian'

In [149]:
len(front_raw)

9

In [150]:
del front_raw[4]

In [151]:
front_raw

['Greg', 'Julian', 'Seline', 'Oceane', 'Muhammad', 'Dave', 'Beven', 'Alex']

## Processing collections in one hit - for loop

In [153]:
for name in front_raw:
    print('Hello', name)

Hello Greg
Hello Julian
Hello Seline
Hello Oceane
Hello Muhammad
Hello Dave
Hello Beven
Hello Alex

In [154]:
heights = [172, 170, 180, 193, 182]

Calculate heights in feet and iches for each height

In [155]:
for h in heights:
    meters = h / 100
    print(unit_conversion.metric_to_imperial(meters))

(5.0, 7.7165354330708595)
(5.0, 6.929133858267718)
(5.0, 10.866141732283467)
(6.0, 3.9842519685039406)
(5.0, 11.653543307086608)

### Exercise: convert temperatures from C to F

In [165]:
def centigrade_to_Fehrenheit(degrees):
    return (degrees * (9 / 5)) +32

In [182]:
temprature_C = [21, 27, 20, 21, 20, 23, 22, 32]

In [187]:
results = []
for t in temprature_C:
    F = centigrade_to_Fehrenheit(t)
    results.append(F)

In [188]:
results

[69.80000000000001, 80.6, 68.0, 69.80000000000001, 68.0, 73.4, 71.6, 89.6]

In [189]:
import glob                      # dealing with lots of files instead of small lists
import os

file_size = []
for path in glob.glob('Data/*.csv'):
    file_size.append(os.path.getsize(path))

In [190]:
file_size

[211744,
 20524,
 84921,
 13735,
 48168,
 7046,
 172049,
 30973,
 100059,
 6009,
 99777,
 36071,
 13735,
 3168,
 3356,
 4384]

# Web requests - Key collections
### (page 111 in the book)

In [191]:
url = 'https://www.google.com'

In [192]:
import requests

In [193]:
requests.get(url)

In [194]:
response = requests.get(url)

In [195]:
response.headers

{'Date': 'Mon, 15 Oct 2018 05:29:00 GMT', 'Expires': '-1', 'Cache-Control': 'private, max-age=0', 'Content-Type': 'text/html; charset=ISO-8859-1', 'P3P': 'CP="This is not a P3P policy! See g.co/p3phelp for more info."', 'Content-Encoding': 'gzip', 'Server': 'gws', 'X-XSS-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'Set-Cookie': '1P_JAR=2018-10-15-05; expires=Wed, 14-Nov-2018 05:29:00 GMT; path=/; domain=.google.com, NID=141=ht-qtHUgBQjF5zPVKSlkhK6Q6R_HXFtIb8VPGOIeZP97uerkTpOjGrRa8pc-haiZR1VUW6keeJUo28zkXXWGgVGueQn5VZ3TBD8VvtstQAXtwHBo0BCinBpbmgw-8G76; expires=Tue, 16-Apr-2019 05:29:00 GMT; path=/; domain=.google.com; HttpOnly', 'Alt-Svc': 'quic=":443"; ma=2592000; v="44,43,39,35"', 'Transfer-Encoding': 'chunked'}

A Python dictionary is a map of keys to values. A dictionary looks like:
    
    {Key: value, Key: value}
    
Keys are unique, values are not.

In [196]:
response.headers['content-type']

'text/html; charset=ISO-8859-1'

## APIs

In [ ]:
%load http://bit.ly/pythoncharmersurls  # the % does not actually run the code. it just brings the information to the notebook for you to check first.
                                        # when you run this cell, the next cell will appear.
                                        # run the next cell again to confirm the URL and API key

In [199]:
# %load http://bit.ly/pythoncharmersurls
OpenWeatherMapApiKey="d1741b0c4ca70aeb629424a1ddcf28a1"
url="https://api.openweathermap.org/data/2.5/weather?q={city_name},{country_code}"
postgresqlTrainingDatabase="gis.ceebzpnip62q.ap-southeast-2.rds.amazonaws.com:5432/training"

In [201]:
response = requests.get(url)

In [202]:
response.headers['content-type']

'application/json; charset=utf-8'

In [203]:
data = response.json()  # turns text that looks like a dictionary into a dictionary

{'cod': 401,
 'message': 'Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.'}

### The long and wrong way to fix the error (code: 401)

In [204]:
url

'https://api.openweathermap.org/data/2.5/weather?q={city_name},{country_code}'

In [205]:
url = 'https://api.openweathermap.org/data/2.5/weather?q=Melbourne,AU&appid=' + OpenWeatherMapApiKey

In [206]:
url

'https://api.openweathermap.org/data/2.5/weather?q=Melbourne,AU&appid=d1741b0c4ca70aeb629424a1ddcf28a1'

In [207]:
requests.get(url)

In [208]:
response = requests.get(url)

In [209]:
response.json()

{'coord': {'lon': 144.96, 'lat': -37.81},
 'weather': [{'id': 800,
   'main': 'Clear',
   'description': 'clear sky',
   'icon': '01d'}],
 'base': 'stations',
 'main': {'temp': 299.5,
  'pressure': 1013,
  'humidity': 31,
  'temp_min': 299.15,
  'temp_max': 300.15},
 'visibility': 10000,
 'wind': {'speed': 8.7, 'deg': 20, 'gust': 14.4},
 'clouds': {'all': 0},
 'dt': 1539581520,
 'sys': {'type': 1,
  'id': 8201,
  'message': 0.007,
  'country': 'AU',
  'sunrise': 1539545717,
  'sunset': 1539592637},
 'id': 2158177,
 'name': 'Melbourne',
 'cod': 200}

#### Exercise:  What temperature is in the city where you were born?

In [214]:
url = 'https://api.openweathermap.org/data/2.5/weather?q=Alexandria,EG&appid=' + OpenWeatherMapApiKey

In [215]:
response = requests.get(url)
weather = response.json()
weather['main']['temp']-273.15 ## to convert it to celsius

18.450000000000045